version: '3.8'
services:
  db:
    container_name: course-erp-db
    image: postgres:14.5
    #    image: postgres:12.20-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_HOST_AUTH_METHOD:trust
#      - POSTGRES_MULTIPLE_DATABASES="language-learning-db"
    ports:
      - '5432:5432'
    volumes:
      - ../../docker-volumes/course-erp-db:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL","pg_isready -U postgress" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#  networks:
#    -webperside-network